### ISSUE TITLE
Transaction Success but order not updated.

### ISSUE THREAD

**Issue by stagfoo** [jvcl/commweb-woocommerce#1]
Hey Buddy,
Firstly this is great and works pretty good, I seem to have run into a bug with the respond sent to woo at the end.
So basically the whole process goes through and i get a result from VPC 
`0` which goes into `getResponseDescription` and returns `Transaction Successful`
however the response woo gets isn't correct and it things it has failed.

`Payment not completed. CommWeb response: Transaction Successful`

I have been trying to debug but my logs aren't coming out either  ''^_^

any help would be appreciated

**Comment by jvcl** [comment]
Hello! I pushed a fix for that problem. I had the same issue with other store.

Cheers!
Jorge
