### ISSUE TITLE
Need to convert plugin from MD5 to SHA256

### ISSUE THREAD

**Issue by Rcreators** [jvcl/commweb-woocommerce#2]
As Commonwealth Bank is not supporting MD5 encryption, Plugin is stopped working. Can you update the plugin to work with SHA and update it ?

**Comment by jvcl** [comment]
Hi @Rcreators 

Do you have the sample documentation from the Commonwealth Bank?

Thanks

**Comment by chris-gna** [comment]
Hi,

Does that mean it is not working anymore?

Best Regards,
Chris

**Comment by jvcl** [comment]
@chris-gna @chris-gna I added a [new branch](https://github.com/jvcl/commweb-woocommerce/tree/SHA256) with a fix for the SHA256 issue, [specifically this commit](https://github.com/jvcl/commweb-woocommerce/commit/a13b7c4f6e0f462671b643e9e59d8f4cb1f6178a) Let me know if you can test it.

Jorge
